# Generated by Django 4.1.5 on 2023-01-02 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentilatorShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='introYear',
            field=models.IntegerField(null=True),
        ),
    ]
